name = "LDPCStorage"
uuid = "d46d874d-5773-4ce9-8adb-568101dc8882"
authors = ["Adomas Baliuka <A.Baliuka@physik.uni-muenchen.de>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
